In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

sns.set(style="whitegrid")

In [6]:
try:
    crop_df=pd.read_csv(r"D:\Crop Yield Prediction\all_states_crop_data.csv")
    weather_df=pd.read_csv("D:\Crop Yield Prediction\weather_dataset\weather_2000_2023\master_weather_india_2000_2023.csv")
except:
    print("File not Found")

In [7]:
crop_df.shape

(441867, 8)

In [8]:
crop_df.columns

Index(['State', 'Crop', 'District', 'Season', 'Area_(Hectare)', 'Year',
       'Production_(Tonnes)', 'Yield_(Ton./Ha.)'],
      dtype='object')

In [9]:
crop_df.dtypes

State                   object
Crop                    object
District                object
Season                  object
Area_(Hectare)         float64
Year                    object
Production_(Tonnes)    float64
Yield_(Ton./Ha.)        object
dtype: object

In [10]:
crop_df.isnull().sum()

State                       0
Crop                        0
District                    0
Season                      0
Area_(Hectare)         213367
Year                        0
Production_(Tonnes)    216094
Yield_(Ton./Ha.)       213367
dtype: int64

In [11]:
crop_df["State"].unique()

array(['andaman crop', 'andhra pradesh crop.csv',
       'arunachal pradesh crop.csv', 'assam crop.csv', 'bihar crop.csv',
       'chhattisgarh crop.csv', 'dadra&nagar crop.csv',
       'daman&diu crop.csv', 'delhi crop.csv', 'goa crop.csv',
       'gujarat crop.csv', 'haryana crop.csv',
       'himachal pradesh crop.csv', 'j&k crop.csv', 'jharkhand crop.csv',
       'karnataka crop.csv', 'Kerla crop.csv', 'ladakh crop.csv',
       'maharashtra crop.csv', 'manipur crop.csv', 'meghalaya crop.csv',
       'mizoram crop.csv', 'mp crop.csv', 'Nagaland crop.csv',
       'Odisha crop.csv', 'Puducherry crop.csv', 'Punjab crop.csv',
       'Rajasthan crop.csv', 'Sikkim crop.csv', 'Tamil Nadu crop.csv',
       'Telangana crop.csv', 'Tripura crop.csv', 'Uttarakhand crop.csv',
       'Uttar Pradesh crop.csv', 'West Bengal crop.csv'], dtype=object)

In [12]:
crop_df["State"]=crop_df["State"].str.extract(r'(.*?)\s+crop')

In [13]:
crop_df["State"].unique()

array(['andaman', 'andhra pradesh', 'arunachal pradesh', 'assam', 'bihar',
       'chhattisgarh', 'dadra&nagar', 'daman&diu', 'delhi', 'goa',
       'gujarat', 'haryana', 'himachal pradesh', 'j&k', 'jharkhand',
       'karnataka', 'Kerla', 'ladakh', 'maharashtra', 'manipur',
       'meghalaya', 'mizoram', 'mp', 'Nagaland', 'Odisha', 'Puducherry',
       'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana',
       'Tripura', 'Uttarakhand', 'Uttar Pradesh', 'West Bengal'],
      dtype=object)

In [14]:
crop_df["State"].replace({"j&k":"Jammu and Kashmir","dadra&nagar":"dadar and Nagar Haveli",
                          "daman&diu":"daman and diu","mp":"madhya pradesh","andaman":"andman and nicobars island"
                          },inplace=True)

In [15]:
crop_df["State"]=crop_df["State"].str.title()

In [16]:
crop_df["State"].nunique()

35

In [17]:
crop_df.columns=(
    crop_df.columns
    .str.strip()
    .str.upper()
    .str.replace(" ","_")
    .str.replace(".","")
    .str.replace("(","")
    .str.replace(")","")
    .str.replace(".","")
    
)

In [18]:
crop_df.rename(columns={'YIELD_TON/HA':'YIELD_TON_HA'},inplace=True)

In [19]:
crop_df.columns

Index(['STATE', 'CROP', 'DISTRICT', 'SEASON', 'AREA_HECTARE', 'YEAR',
       'PRODUCTION_TONNES', 'YIELD_TON_HA'],
      dtype='object')

In [20]:
crop_df["YEAR"].unique()

array(['2000-2001', '2001-2002', '2002-2003', '2003-2004', '2004-2005',
       '2005-2006', '2006-2007', '2007-2008', '2008-2009', '2009-2010',
       '2010-2011', '2011-2012', '2012-2013', '2013-2014', '2014-2015',
       '2015-2016', '2016-2017', '2017-2018', '2018-2019', '2019-2020',
       '2020-2021', '2021-2022', '2022-2023'], dtype=object)

In [21]:
crop_df["YEAR"] = crop_df["YEAR"].str.split("-").str[0].astype(int)

In [22]:
text_cols=["STATE","DISTRICT","CROP","SEASON"]
for col in text_cols:
    if col in crop_df.columns:
        (crop_df[col].astype(str)
        .str.strip()
        .str.title()
        )

In [23]:
crop_df.isnull().sum()

STATE                     0
CROP                      0
DISTRICT                  0
SEASON                    0
AREA_HECTARE         213367
YEAR                      0
PRODUCTION_TONNES    216094
YIELD_TON_HA         213367
dtype: int64

In [24]:
numeric_cols=crop_df.columns.difference(
    ["STATE","DISTRICT","YEAR","SEASON","CROP"]
)
for col in numeric_cols:
    crop_df[col]=pd.to_numeric(crop_df[col],errors="coerce")

In [25]:
crop_df.isnull().sum()

STATE                     0
CROP                      0
DISTRICT                  0
SEASON                    0
AREA_HECTARE         213367
YEAR                      0
PRODUCTION_TONNES    216094
YIELD_TON_HA         213370
dtype: int64

In [26]:
crop_df=crop_df.dropna()

In [27]:
crop_df.shape

(225770, 8)

In [28]:
crop_df["SEASON"].unique()

array(['Kharif', 'Rabi', 'Autumn', 'Summer', 'Winter'], dtype=object)

In [29]:
crop_df["SEASON"]=crop_df["SEASON"].replace("Winter","Rabi")

In [30]:
crop_df["SEASON"].unique()

array(['Kharif', 'Rabi', 'Autumn', 'Summer'], dtype=object)

WEATHER DATASET

In [31]:
weather_df.shape

(315576, 12)

In [32]:
weather_df.dtypes

Unnamed: 0            object
T2M                  float64
T2M_MIN              float64
T2M_MAX              float64
PRECTOTCORR          float64
RH2M                 float64
WS2M                 float64
ALLSKY_SFC_SW_DWN    float64
PS                   float64
city                  object
latitude             float64
longitude            float64
dtype: object

In [33]:
weather_df.isnull().sum()

Unnamed: 0           0
T2M                  0
T2M_MIN              0
T2M_MAX              0
PRECTOTCORR          0
RH2M                 0
WS2M                 0
ALLSKY_SFC_SW_DWN    0
PS                   0
city                 0
latitude             0
longitude            0
dtype: int64

In [34]:
weather_df.columns

Index(['Unnamed: 0', 'T2M', 'T2M_MIN', 'T2M_MAX', 'PRECTOTCORR', 'RH2M',
       'WS2M', 'ALLSKY_SFC_SW_DWN', 'PS', 'city', 'latitude', 'longitude'],
      dtype='object')

In [35]:
weather_df.rename(columns={'Unnamed: 0':'DATE'},inplace=True)

In [36]:
weather_df.columns

Index(['DATE', 'T2M', 'T2M_MIN', 'T2M_MAX', 'PRECTOTCORR', 'RH2M', 'WS2M',
       'ALLSKY_SFC_SW_DWN', 'PS', 'city', 'latitude', 'longitude'],
      dtype='object')

In [37]:
weather_df.columns = (
    weather_df.columns
    .str.strip()
    .str.upper()
    .str.replace(" ", "_")
)

In [38]:
weather_df.columns

Index(['DATE', 'T2M', 'T2M_MIN', 'T2M_MAX', 'PRECTOTCORR', 'RH2M', 'WS2M',
       'ALLSKY_SFC_SW_DWN', 'PS', 'CITY', 'LATITUDE', 'LONGITUDE'],
      dtype='object')

In [39]:
weather_df["DATE"]=pd.to_datetime(weather_df["DATE"],errors='coerce')

In [40]:
weather_df["YEAR"]=weather_df["DATE"].dt.year
weather_df["MONTH"]=weather_df["DATE"].dt.month

In [41]:
weather_numeric_col=weather_df.columns.difference(
    ["DATE", "YEAR", "MONTH","CITY"]
)

In [42]:
for col in weather_numeric_col:
    weather_df[col]=pd.to_numeric(
        weather_df[col],
        errors='coerce'
    )

In [43]:
weather_df=weather_df.sort_values("DATE")

In [44]:
weather_df.columns

Index(['DATE', 'T2M', 'T2M_MIN', 'T2M_MAX', 'PRECTOTCORR', 'RH2M', 'WS2M',
       'ALLSKY_SFC_SW_DWN', 'PS', 'CITY', 'LATITUDE', 'LONGITUDE', 'YEAR',
       'MONTH'],
      dtype='object')

In [45]:
weather_df.rename(columns={"CITY":"STATE"},inplace=True)

In [47]:
weather_monthly = (
    weather_df
    .groupby(["STATE", "YEAR", "MONTH"])
    .agg({
        "T2M": "mean",
        "T2M_MIN": "mean",
        "T2M_MAX": "mean",
        "RH2M": "mean",
        "WS2M": "mean",
        "PRECTOTCORR": "sum",
        "ALLSKY_SFC_SW_DWN": "mean"
    })
    .reset_index()
)

In [48]:
print("\nFinal Daily Weather Shape:", weather_df.shape)
print("\nFinal Yearly monthly Shape:", weather_monthly.shape)
print("\nMissing values (Yearly):")
print(weather_monthly.isnull().sum())

Final Daily Weather Shape: (315576, 14)

Final Yearly monthly Shape: (10368, 10)

Missing values (Yearly):
STATE                0
YEAR                 0
MONTH                0
T2M                  0
T2M_MIN              0
T2M_MAX              0
RH2M                 0
WS2M                 0
PRECTOTCORR          0
ALLSKY_SFC_SW_DWN    0
dtype: int64

In [49]:
crop_rabi=crop_df[crop_df["SEASON"]=="Rabi"]
crop_kharif=crop_df[crop_df["SEASON"]=="Kharif"]
crop_summer=crop_df[crop_df["SEASON"]=="Summer"]
crop_autumn=crop_df[crop_df["SEASON"]=="Autumn"]

In [50]:
crop_df["YEAR"].unique()

array([2000, 2001, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015,
       2016, 2017, 2018, 2019, 2002, 2003, 2004, 2005, 2006, 2020, 2021,
       2022])

In [51]:
SEASON_MONTHS = {
    "Kharif":  [6, 7, 8, 9],
    "Autumn":  [9, 10, 11],
    "Rabi":    [12, 1, 2, 3],
    "Summer":  [3, 4, 5]
}

In [52]:

def assign_crop_year(season, month, year):
    if season == "Rabi" and month in [1, 2, 3]:
        return year - 1
    else:
        return year

In [53]:
rabi_weather = weather_df[weather_df["MONTH"].isin(SEASON_MONTHS["Rabi"])].copy()

rabi_weather["SEASON"] = "Rabi"
rabi_weather["cROP_YEAR"] = rabi_weather.apply(
    lambda r: assign_crop_year("Rabi", r["MONTH"], r["YEAR"]),
    axis=1
)

In [54]:
rabi_weather.columns

Index(['DATE', 'T2M', 'T2M_MIN', 'T2M_MAX', 'PRECTOTCORR', 'RH2M', 'WS2M',
       'ALLSKY_SFC_SW_DWN', 'PS', 'STATE', 'LATITUDE', 'LONGITUDE', 'YEAR',
       'MONTH', 'SEASON', 'cROP_YEAR'],
      dtype='object')

In [55]:
kharif_weather = weather_df[weather_df["MONTH"].isin(SEASON_MONTHS["Kharif"])].copy()
kharif_weather["SEASON"] = "Kharif"

In [56]:
autumn_weather = weather_df[weather_df["MONTH"].isin(SEASON_MONTHS["Autumn"])].copy()
autumn_weather["SEASON"] = "Autumn"

In [57]:
summer_weather = weather_df[weather_df["MONTH"].isin(SEASON_MONTHS["Summer"])].copy()
summer_weather["SEASON"] = "Summer"

In [60]:
weather_agg = {
    "T2M": "mean",
    "T2M_MIN": "mean",
    "T2M_MAX": "mean",
    "RH2M": "mean",
    "WS2M": "mean",
    "PRECTOTCORR": "sum",
    "ALLSKY_SFC_SW_DWN": "mean"
}

def aggregate_weather(df):
    return (
        df
        .groupby(["STATE","YEAR","SEASON"])
        .agg(weather_agg)
        .reset_index()
    )

rabi_weather_agg   = aggregate_weather(rabi_weather)
kharif_weather_agg = aggregate_weather(kharif_weather)
autumn_weather_agg = aggregate_weather(autumn_weather)
summer_weather_agg = aggregate_weather(summer_weather)

In [61]:
rabi_weather_agg.columns

Index(['STATE', 'YEAR', 'SEASON', 'T2M', 'T2M_MIN', 'T2M_MAX', 'RH2M', 'WS2M',
       'PRECTOTCORR', 'ALLSKY_SFC_SW_DWN'],
      dtype='object')

In [62]:
rabi_merged_df= crop_rabi.merge(
    rabi_weather_agg,
    left_on=["STATE","YEAR", "SEASON"],
    right_on=["STATE","YEAR", "SEASON"],
    how="inner"
)

In [63]:
kharif_merged_df= crop_kharif.merge(
    kharif_weather_agg,
    left_on=["STATE","YEAR", "SEASON"],
    right_on=["STATE","YEAR", "SEASON"],
    how="inner"
)

In [64]:
autumn_merged_df= crop_autumn.merge(
    autumn_weather_agg,
    left_on=["STATE","YEAR", "SEASON"],
    right_on=["STATE","YEAR", "SEASON"],
    how="inner"
)

In [65]:
summer_merged_df= crop_summer.merge(
    summer_weather_agg,
    left_on=["STATE","YEAR", "SEASON"],
    right_on=["STATE","YEAR", "SEASON"],
    how="inner"
)

In [66]:
rabi_merged_df.columns

Index(['STATE', 'CROP', 'DISTRICT', 'SEASON', 'AREA_HECTARE', 'YEAR',
       'PRODUCTION_TONNES', 'YIELD_TON_HA', 'T2M', 'T2M_MIN', 'T2M_MAX',
       'RH2M', 'WS2M', 'PRECTOTCORR', 'ALLSKY_SFC_SW_DWN'],
      dtype='object')

In [67]:
rabi_merged_df.dtypes

STATE                 object
CROP                  object
DISTRICT              object
SEASON                object
AREA_HECTARE         float64
YEAR                   int64
PRODUCTION_TONNES    float64
YIELD_TON_HA         float64
T2M                  float64
T2M_MIN              float64
T2M_MAX              float64
RH2M                 float64
WS2M                 float64
PRECTOTCORR          float64
ALLSKY_SFC_SW_DWN    float64
dtype: object

In [68]:
numeric_df = rabi_merged_df.select_dtypes(include=["int64", "float64"])

In [69]:
corr_matrix = numeric_df.corr()
corr_matrix

,AREA_HECTARE,YEAR,PRODUCTION_TONNES,YIELD_TON_HA,T2M,T2M_MIN,T2M_MAX,RH2M,WS2M,PRECTOTCORR,ALLSKY_SFC_SW_DWN
AREA_HECTARE,1.000000,-0.002091,0.788784,-0.000349,0.006486,-0.035603,0.046411,-0.193472,0.133250,-0.067292,0.038827
YEAR,-0.002091,1.000000,0.045398,0.088134,-0.050971,0.016689,-0.120003,0.271619,-0.042332,0.201309,-0.226245
PRODUCTION_TONNES,0.788784,0.045398,1.000000,0.178292,-0.028686,-0.051757,-0.005682,-0.114671,0.100652,-0.010786,-0.050027
YIELD_TON_HA,-0.000349,0.088134,0.178292,1.000000,0.056743,0.055246,0.043320,0.027150,0.041247,-0.016782,-0.066743
T2M,0.006486,-0.050971,-0.028686,0.056743,1.000000,0.953456,0.972254,-0.133069,0.387282,-0.411267,0.653649
T2M_MIN,-0.035603,0.016689,-0.051757,0.055246,0.953456,1.000000,0.865056,0.095871,0.301621,-0.245057,0.586675
T2M_MAX,0.046411,-0.120003,-0.005682,0.043320,0.972254,0.865056,1.000000,-0.316207,0.430636,-0.526782,0.680543
RH2M,-0.193472,0.271619,-0.114671,0.027150,-0.133069,0.095871,-0.316207,1.000000,-0.513232,0.516486,-0.252281
WS2M,0.133250,-0.042332,0.100652,0.041247,0.387282,0.301621,0.430636,-0.513232,1.000000,-0.246338,0.382312
PRECTOTCORR,-0.067292,0.201309,-0.010786,-0.016782,-0.411267,-0.245057,-0.526782,0.516486,-0.246338,1.000000,-0.416556
ALLSKY_SFC_SW_DWN,0.038827,-0.226245,-0.050027,-0.066743,0.653649,0.586675,0.680543,-0.252281,0.382312,-0.416556,1.000000

In [70]:
final_df = pd.concat(
    [kharif_merged_df, rabi_merged_df, autumn_merged_df, summer_merged_df],
    axis=0,
    ignore_index=True
)

print("Final dataset shape:", final_df.shape)

Final dataset shape: (220745, 15)

In [71]:
final_df.head(10)

,STATE,CROP,DISTRICT,SEASON,AREA_HECTARE,YEAR,PRODUCTION_TONNES,YIELD_TON_HA,T2M,T2M_MIN,T2M_MAX,RH2M,WS2M,PRECTOTCORR,ALLSKY_SFC_SW_DWN
0,Andhra Pradesh,Arhar/Tur,Anantapur,Kharif,30693.0,2000,7888.0,0.26,27.643525,24.591475,31.341639,81.111148,2.678115,832.85,17.173115
1,Andhra Pradesh,Arhar/Tur,Chittoor,Kharif,6032.0,2000,2172.0,0.36,27.643525,24.591475,31.341639,81.111148,2.678115,832.85,17.173115
2,Andhra Pradesh,Arhar/Tur,East godavari,Kharif,1861.0,2000,953.0,0.51,27.643525,24.591475,31.341639,81.111148,2.678115,832.85,17.173115
3,Andhra Pradesh,Arhar/Tur,Guntur,Kharif,42388.0,2000,16786.0,0.40,27.643525,24.591475,31.341639,81.111148,2.678115,832.85,17.173115
4,Andhra Pradesh,Arhar/Tur,Kadapa,Kharif,15189.0,2000,8369.0,0.55,27.643525,24.591475,31.341639,81.111148,2.678115,832.85,17.173115
5,Andhra Pradesh,Arhar/Tur,Krishna,Kharif,9762.0,2000,6316.0,0.65,27.643525,24.591475,31.341639,81.111148,2.678115,832.85,17.173115
6,Andhra Pradesh,Arhar/Tur,Kurnool,Kharif,38108.0,2000,16996.0,0.45,27.643525,24.591475,31.341639,81.111148,2.678115,832.85,17.173115
7,Andhra Pradesh,Arhar/Tur,Prakasam,Kharif,95553.0,2000,60198.0,0.63,27.643525,24.591475,31.341639,81.111148,2.678115,832.85,17.173115
8,Andhra Pradesh,Arhar/Tur,Spsr nellore,Kharif,2063.0,2000,1143.0,0.55,27.643525,24.591475,31.341639,81.111148,2.678115,832.85,17.173115
9,Andhra Pradesh,Arhar/Tur,Srikakulam,Kharif,1758.0,2000,974.0,0.55,27.643525,24.591475,31.341639,81.111148,2.678115,832.85,17.173115

In [72]:
final_df.columns

Index(['STATE', 'CROP', 'DISTRICT', 'SEASON', 'AREA_HECTARE', 'YEAR',
       'PRODUCTION_TONNES', 'YIELD_TON_HA', 'T2M', 'T2M_MIN', 'T2M_MAX',
       'RH2M', 'WS2M', 'PRECTOTCORR', 'ALLSKY_SFC_SW_DWN'],
      dtype='object')

In [73]:
final_df.isnull().sum()

STATE                0
CROP                 0
DISTRICT             0
SEASON               0
AREA_HECTARE         0
YEAR                 0
PRODUCTION_TONNES    0
YIELD_TON_HA         0
T2M                  0
T2M_MIN              0
T2M_MAX              0
RH2M                 0
WS2M                 0
PRECTOTCORR          0
ALLSKY_SFC_SW_DWN    0
dtype: int64

In [74]:
final_df.to_csv("Crop_Weather_data.csv",index=False)